apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fleet-telemetry.fullname" . }}
  labels:
    role: api
    service: fleet-telemetry
  {{- include "fleet-telemetry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      role: api
      service: fleet-telemetry
    {{- include "fleet-telemetry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        role: api
        service: fleet-telemetry
      {{- include "fleet-telemetry.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - command:
        - /fleet-telemetry
        - -config=/etc/fleet-telemetry/config.json
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /metrics
            port: {{ .Values.config.metrics.port }}
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 10
        name: fleet-telemetry
        ports:
        - containerPort: {{ .Values.config.profile.port }}
          name: profile
          protocol: TCP
        - containerPort: {{ .Values.config.port }}
          name: https
          protocol: TCP
        - containerPort: {{ .Values.config.metrics.port }}
          name: metrics
          protocol: TCP
        resources: {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /etc/fleet-telemetry/
          name: config
        - mountPath: /etc/tesla/certs/server
          name: server-certs
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      volumes:
      - name: config
        projected:
          sources:
          - configMap:
              name: {{ include "fleet-telemetry.fullname" . }}
      - name: server-certs
        projected:
          sources:
          - secret:
              name: {{ .Values.tlsSecret.name | default (printf "%s" (include "fleet-telemetry.fullname" .)) }}