apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "fleet-telemetry.fullname" . }}
  labels:
    {{- include "fleet-telemetry.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.tlsSecret.name | default (printf "%s" (include "fleet-telemetry.fullname" .)) }}
    template:
      type: kubernetes.io/tls
  data:
  - secretKey: tls.crt
    remoteRef:
      key: {{ .Values.externalSecrets.secretName | quote }}
      property: tlsCrt
      version: "AWSCURRENT"
  - secretKey: tls.key
    remoteRef:
      key: {{ .Values.externalSecrets.secretName | quote }}
      property: tlsKey
      version: "AWSCURRENT"
